# Generated by Django 5.0.3 on 2024-04-30 09:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0005_movie_title_movie_year_alter_movie_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordResetRequest',
        ),
    ]
