# Generated by Django 5.0.4 on 2024-05-03 17:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_api', '0008_alter_movie_actors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='current_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
